name: env.fl
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2023.05.30=h06a4308_0
  - certifi=2023.7.22=py39h06a4308_0
  - cudatoolkit=11.1.1=h6406543_8
  - cycler=0.10.0=py39h06a4308_0
  - dbus=1.13.18=hb2f20db_0
  - decorator=4.4.2=pyhd3eb1b0_0
  - expat=2.4.1=h2531618_2
  - ffmpeg=4.3=hf484d3e_0
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.10.4=h0708190_1
  - giflib=5.2.1=h36c2ea0_2
  - glib=2.69.0=h5202010_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - intel-openmp=2021.2.0=h06a4308_610
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.3.1=py39h2531618_0
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libblas=3.9.0=9_mkl
  - libcblas=3.9.0=9_mkl
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=9_mkl
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtiff=4.2.0=h85742a9_0
  - libuuid=1.0.3=h1bed415_2
  - libwebp=1.2.0=h89dd481_0
  - libwebp-base=1.2.0=h7f98852_2
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.12=h03d6c58_0
  - lz4-c=1.9.3=h9c3ff4c_0
  - matplotlib=3.3.4=py39h06a4308_0
  - matplotlib-base=3.3.4=py39h62a2d02_0
  - mkl=2021.2.0=h06a4308_296
  - mkl-service=2.3.0=py39h27cfd23_1
  - mkl_fft=1.3.0=py39h42c9631_2
  - mkl_random=1.2.1=py39ha9443f7_2
  - ncurses=6.2=he6710b0_1
  - nettle=3.6=he412f7d_0
  - ninja=1.10.2=h4bd325d_0
  - numpy-base=1.20.2=py39hfae3a4d_0
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1v=h7f8727e_0
  - pcre=8.45=h295c915_0
  - pip=21.1.3=py39h06a4308_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py39h2531618_6
  - python=3.9.5=h12debd9_4
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - qt=5.9.7=h5867ecd_1
  - readline=8.1=h27cfd23_0
  - setuptools=52.0.0=py39h06a4308_0
  - sip=4.19.13=py39h2531618_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.10=hbc83047_0
  - torchaudio=0.8.0=py39
  - torchvision=0.9.0=py39_cu111
  - tornado=6.1=py39h27cfd23_0
  - tqdm=4.62.1=pyhd3eb1b0_1
  - tzdata=2021a=h52ac0ba_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=ha95c52a_0
  - pip:
    - absl-py==1.4.0
    - accelerate==0.21.0
    - addict==2.4.0
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - alembic==1.10.4
    - appdirs==1.4.4
    - asttokens==2.4.1
    - async-timeout==4.0.2
    - attrs==23.1.0
    - audioread==3.0.1
    - cachetools==5.3.0
    - cffi==1.16.0
    - charset-normalizer==2.0.4
    - click==8.1.7
    - cmaes==0.9.1
    - cmake==3.27.1
    - colorlog==6.7.0
    - comm==0.1.4
    - cython==0.29.34
    - datasets==2.18.0
    - dill==0.3.6
    - docker-pycreds==0.4.0
    - evaluate==0.4.0
    - exceptiongroup==1.1.3
    - executing==2.0.1
    - filelock==3.12.2
    - frozenlist==1.3.3
    - fsspec==2023.6.0
    - fvcore==0.1.5.post20221221
    - gitdb==4.0.11
    - gitpython==3.1.41
    - google-auth==2.17.3
    - google-auth-oauthlib==1.0.0
    - greenlet==2.0.2
    - grpcio==1.54.0
    - hdbscan==0.8.40
    - huggingface-hub==0.21.3
    - idna==3.2
    - imageio==2.27.0
    - importlib-metadata==6.5.0
    - pip-install==1.3.5
    - iopath==0.1.10
    - ipython==8.17.2
    - ipywidgets==8.1.1
    - jedi==0.19.1
    - jinja2==3.1.2
    - jiwer==3.0.3
    - joblib==1.2.0
    - jsonlines==3.1.0
    - jsonpatch==1.32
    - jsonpointer==2.3
    - jupyterlab-widgets==3.0.9
    - lazy-loader==0.2
    - librosa==0.10.1
    - lit==16.0.6
    - llvmlite==0.41.1
    - mako==1.2.4
    - markdown==3.4.3
    - markdown-it-py==2.2.0
    - markupsafe==2.1.2
    - matplotlib-inline==0.1.6
    - mdurl==0.1.2
    - mmengine==0.7.2
    - mpmath==1.3.0
    - msgpack==1.0.7
    - multidict==6.0.4
    - multiprocess==0.70.14
    - mxnet-cu102==1.9.1
    - networkx==3.1
    - numba==0.58.1
    - numpy==1.24.4
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - oauthlib==3.2.2
    - opacus==1.4.0
    - opencv-python==4.7.0.72
    - opt-einsum==3.3.0
    - optuna==3.1.1
    - packaging==23.1
    - pandas==1.3.2
    - parso==0.8.3
    - peft==0.4.0
    - pexpect==4.8.0
    - pillow==9.5.0
    - platformdirs==4.1.0
    - plotly==5.14.1
    - pooch==1.8.0
    - portalocker==2.8.2
    - prompt-toolkit==3.0.39
    - protobuf==4.22.3
    - psutil==5.9.5
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyarrow==12.0.1
    - pyarrow-hotfix==0.6
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.21
    - pygments==2.15.1
    - graphviz==0.8.4
    - pytorch-metric-learning==2.3.0
    - pytz==2021.1
    - pywavelets==1.4.1
    - pyyaml==6.0
    - rapidfuzz==3.5.2
    - regex==2023.6.3
    - requests==2.26.0
    - requests-oauthlib==1.3.1
    - responses==0.18.0
    - rich==13.3.4
    - rsa==4.9
    - safetensors==0.3.1
    - scikit-image==0.20.0
    - scikit-learn==1.2.2
    - scipy==1.9.1
    - seaborn==0.11.2
    - sentry-sdk==1.40.2
    - setproctitle==1.3.3
    - smmap==5.0.1
    - soundfile==0.12.1
    - sox==1.4.1
    - soxr==0.3.7
    - sqlalchemy==2.0.10
    - stack-data==0.6.3
    - sympy==1.12
    - tabulate==0.9.0
    - tenacity==8.2.2
    - tensorboard==2.12.2
    - tensorboard-data-server==0.7.0
    - tensorboard-plugin-wit==1.8.1
    - termcolor==2.2.0
    - threadpoolctl==3.1.0
    - tifffile==2023.4.12
    - tokenizers==0.13.3
    - tomli==2.0.1
    - torch==2.0.1
    - torchsummary==1.5.1
    - traitlets==5.13.0
    - transformers==4.32.0
    - triton==2.0.0
    - typing-extensions==4.5.0
    - urllib3==1.26.18
    - visdom==0.2.4
    - vowpalwabbit==9.9.0
    - wandb==0.16.3
    - wcwidth==0.2.9
    - websocket-client==1.5.1
    - werkzeug==2.2.3
    - widgetsnbextension==4.0.9
    - xxhash==3.2.0
    - yacs==0.1.8
    - yapf==0.33.0
    - yarl==1.9.2
    - zipp==3.15.0
prefix: /home/yourhomepath/anaconda3/envs/env.fl
