name: env.fl
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - matplotlib
  - scipy
  - pandas
  - scikit-learn
  - pillow
  - tqdm
  - pyyaml
  - pip:
    - absl-py==2.3.1
    - accelerate==1.10.1
    - addict==2.4.0
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - alembic==1.10.4
    - appdirs==1.4.4
    - asttokens==2.4.1
    - async-timeout==4.0.2
    - attrs==23.1.0
    - audioread==3.0.1
    - cachetools==5.3.0
    - cffi==1.16.0
    - charset-normalizer==3.4.3
    - click==8.1.7
    - cmaes==0.9.1
    - cmake==3.27.1
    - colorlog==6.7.0
    - comm==0.1.4
    - cython==0.29.34
    - datasets==2.18.0
    - d2l
    - dill==0.3.8
    - docker-pycreds==0.4.0
    - evaluate==0.4.0
    - exceptiongroup==1.1.3
    - executing==2.0.1
    - filelock==3.19.1
    - frozenlist==1.3.3
    - fsspec==2024.2.0
    - fvcore==0.1.5.post20221221
    - gitdb==4.0.11
    - gitpython==3.1.41
    - google-auth==2.17.3
    - google-auth-oauthlib==1.0.0
    - greenlet==2.0.2
    - grpcio==1.75.1
    - huggingface-hub==0.35.3
    - idna==3.10
    - imageio>=2.33.0
    - importlib-metadata==8.7.0
    - iopath==0.1.10
    - ipython==8.17.2
    - ipywidgets==8.1.1
    - jedi==0.19.1
    - jinja2==3.1.6
    - jiwer==3.0.3
    - joblib==1.2.0
    - jsonlines==3.1.0
    - jsonpatch==1.32
    - jsonpointer==2.3
    - jupyterlab-widgets==3.0.9
    - lazy-loader>=0.4
    - lit==16.0.6
    - llvmlite==0.41.1
    - mako==1.2.4
    - markdown==3.9
    - markdown-it-py==2.2.0
    - markupsafe==3.0.3
    - matplotlib-inline==0.1.6
    - mdurl==0.1.2
    - mmengine==0.7.2
    - mpmath==1.3.0
    - msgpack==1.0.7
    - multidict==6.0.4
    - multiprocess==0.70.14
    - networkx==3.2.1
    - numpy==1.26.4
    - oauthlib==3.2.2
    - opacus==1.4.0
    - opt-einsum==3.3.0
    - optuna==3.1.1
    - packaging==23.1
    - pandas==2.0.3
    - parso==0.8.3
    - peft==0.4.0
    - pexpect==4.8.0
    - pillow==9.5.0
    - platformdirs==4.1.0
    - plotly==5.14.1
    - pooch==1.8.0
    - portalocker==2.8.2
    - prompt-toolkit==3.0.39
    - protobuf==4.25.5
    - psutil==7.1.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyarrow==12.0.1
    - pyarrow-hotfix==0.6
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.21
    - pygments==2.15.1
    - pytorch-metric-learning==2.3.0
    - pytz==2021.1
    - pywavelets==1.4.1
    - pyyaml==6.0
    - rapidfuzz==3.5.2
    - regex==2023.6.3
    - requests==2.32.5
    - requests-oauthlib==1.3.1
    - responses==0.18.0
    - rich==13.3.4
    - rsa==4.9
    - safetensors==0.6.2
    - scikit-image>=0.24.0
    - scikit-learn==1.2.2
    - scipy>=1.13.0
    - seaborn==0.11.2
    - sentry-sdk==1.40.2
    - setproctitle==1.3.3
    - smmap==5.0.1
    - soundfile==0.12.1
    - sqlalchemy==2.0.10
    - stack-data==0.6.3
    - sympy==1.14.0
    - tabulate==0.9.0
    - tenacity==8.2.2
    - tensorboard==2.20.0
    - tensorboard-data-server==0.7.0
    - tensorboard-plugin-wit==1.8.1
    - termcolor==2.2.0
    - threadpoolctl==3.1.0
    - tifffile==2023.4.12
    - tokenizers==0.13.3
    - tomli==2.0.1
    - torch==2.1.0
    - torchvision==0.16.0
    - torchaudio==2.1.0
    - torchsummary==1.5.1
    - torchinfo>=1.8.0
    - traitlets==5.13.0
    - transformers==4.31.0
    - typing-extensions==4.15.0
    - urllib3==2.5.0
    - visdom==0.2.4
    - wandb==0.16.3
    - wcwidth==0.2.9
    - websocket-client==1.5.1
    - werkzeug==3.1.3
    - widgetsnbextension==4.0.9
    - xxhash==3.2.0
    - yacs==0.1.8
    - yapf==0.33.0
    - yarl==1.9.2
    - zipp==3.23.0
    - hf-xet==1.1.10
prefix: /home/yourhomepath/anaconda3/envs/env.fl
#prefix: /Users/liamlian/anaconda3/envs/env.fl