name: env.fl
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.14=hb9d3cd8_0
  - brotli=1.1.0=hb03c661_4
  - brotli-bin=1.1.0=hb03c661_4
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.0=py39h74842e3_2
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dbus=1.13.6=h5008d03_3
  - double-conversion=3.3.1=h5888daf_0
  - expat=2.7.1=hecca717_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.59.1=py39heb7d2ae_0
  - freetype=2.14.1=ha770c72_0
  - graphite2=1.3.14=hecca717_2
  - harfbuzz=11.0.0=h76408a6_0
  - icu=75.1=he02047a_0
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.7=py39h74842e3_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h1aa0949_4
  - lerc=4.0.0=h0aef613_1
  - libblas=3.9.0=37_h4a7cf45_openblas
  - libbrotlicommon=1.1.0=hb03c661_4
  - libbrotlidec=1.1.0=hb03c661_4
  - libbrotlienc=1.1.0=hb03c661_4
  - libcblas=3.9.0=37_h0358290_openblas
  - libclang-cpp20.1=20.1.8=default_h99862b1_4
  - libclang13=21.1.0=default_h746c552_1
  - libcups=2.3.3=hb8b1518_5
  - libdeflate=1.24=h86f0d12_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran-ng=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.0=h2ff4ddf_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=h767d61c_7
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=37_h47877c9_openblas
  - libllvm20=20.1.8=hecd9e04_0
  - libllvm21=21.1.0=hecd9e04_0
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libopengl=1.7.0=ha4b6fd6_2
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h421ea60_1
  - libpq=17.6=h3675c94_2
  - libsqlite=3.50.4=h0c1763c_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libtiff=4.7.1=h8261f1e_0
  - libuuid=2.41.2=he9a06e4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.11.0=he8b52b9_0
  - libxml2=2.13.8=h04c0eec_1
  - libxslt=1.1.43=h7a3aeb2_0
  - libzlib=1.3.1=hb9d3cd8_2
  - matplotlib=3.9.4=py39hf3d152e_0
  - matplotlib-base=3.9.4=py39h16632d1_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - mysql-common=9.0.1=h266115a_6
  - mysql-libs=9.0.1=he0572af_6
  - ncurses=6.5=h2d0b736_3
  - openjpeg=2.5.4=h55fea9a_0
  - openldap=2.6.10=he970967_0
  - openssl=3.5.4=h26f9b46_0
  - pcre2=10.44=hc749103_2
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pyparsing=3.2.3=pyhe01879c_2
  - pyside6=6.9.0=py39h0383914_0
  - python=3.9.23=hc30ae73_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.9=8_cp39
  - qhull=2020.2=h434a139_5
  - qt6-main=6.9.0=h6441bc3_0
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - tk=8.6.13=noxft_hd72426e_102
  - tornado=6.5.2=py39hd399759_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - unicodedata2=16.0.0=py39h8cd3c5a_0
  - wayland=1.24.0=hd6090a7_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - yaml=0.2.5=h280c20c_3
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.3.1
      - accelerate==0.21.0
      - addict==2.4.0
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - alembic==1.10.4
      - appdirs==1.4.4
      - asttokens==2.4.1
      - async-timeout==4.0.2
      - attrs==23.1.0
      - audioread==3.0.1
      - cachetools==5.3.0
      - cffi==1.16.0
      - charset-normalizer==3.4.3
      - click==8.1.7
      - cmaes==0.9.1
      - cmake==3.27.1
      - colorlog==6.7.0
      - comm==0.1.4
      - cython==0.29.34
      - datasets==2.14.0
      - decorator==5.2.1
      - dill==0.3.7
      - docker-pycreds==0.4.0
      - evaluate==0.4.0
      - exceptiongroup==1.1.3
      - executing==2.0.1
      - filelock==3.19.1
      - frozenlist==1.3.3
      - fsspec==2023.6.0
      - fvcore==0.1.5.post20221221
      - gitdb==4.0.11
      - gitpython==3.1.41
      - google-auth==2.17.3
      - google-auth-oauthlib==1.0.0
      - greenlet==2.0.2
      - grpcio==1.75.1
      - hf-xet==1.1.10
      - huggingface-hub==0.35.3
      - idna==3.10
      - imageio==2.27.0
      - importlib-metadata==8.7.0
      - iopath==0.1.10
      - ipython==8.17.2
      - ipywidgets==8.1.1
      - jedi==0.19.1
      - jinja2==3.1.6
      - jiwer==3.0.3
      - joblib==1.2.0
      - jsonlines==3.1.0
      - jsonpatch==1.32
      - jsonpointer==2.3
      - jupyterlab-widgets==3.0.9
      - lazy-loader==0.2
      - lit==16.0.6
      - llvmlite==0.41.1
      - mako==1.2.4
      - markdown==3.9
      - markdown-it-py==2.2.0
      - markupsafe==3.0.3
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - mmengine==0.7.2
      - mpmath==1.3.0
      - msgpack==1.0.7
      - multidict==6.0.4
      - multiprocess==0.70.14
      - networkx==3.2.1
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - opacus==1.4.0
      - opencv-python==4.11.0.86
      - opt-einsum==3.3.0
      - optuna==3.1.1
      - packaging==23.1
      - pandas==2.0.3
      - parso==0.8.3
      - peft==0.6.0
      - pexpect==4.8.0
      - pillow==9.5.0
      - platformdirs==4.1.0
      - plotly==5.14.1
      - pooch==1.8.0
      - portalocker==2.8.2
      - prompt-toolkit==3.0.39
      - protobuf==4.25.5
      - psutil==7.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==10.0.1
      - pyarrow-hotfix==0.6
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pycparser==2.21
      - pygments==2.15.1
      - pytorch-metric-learning==2.3.0
      - pytz==2021.1
      - pywavelets==1.4.1
      - pyyaml==6.0
      - rapidfuzz==3.5.2
      - regex==2023.6.3
      - requests==2.32.5
      - requests-oauthlib==1.3.1
      - responses==0.18.0
      - rich==13.3.4
      - rsa==4.9
      - safetensors==0.6.2
      - scikit-image==0.20.0
      - scikit-learn==1.2.2
      - scipy==1.9.1
      - seaborn==0.11.2
      - sentry-sdk==1.40.2
      - setproctitle==1.3.3
      - smmap==5.0.1
      - soundfile==0.12.1
      - sqlalchemy==2.0.10
      - stack-data==0.6.3
      - sympy==1.14.0
      - tabulate==0.9.0
      - tenacity==8.2.2
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.0
      - tensorboard-plugin-wit==1.8.1
      - termcolor==2.2.0
      - threadpoolctl==3.1.0
      - tifffile==2023.4.12
      - tokenizers==0.13.3
      - tomli==2.0.1
      - torch==2.1.0
      - torchaudio==2.1.0
      - torchsummary==1.5.1
      - torchinfo==1.8.0
      - torchvision==0.16.0
      - traitlets==5.13.0
      - transformers==4.32.0
      - triton==2.1.0
      - typing-extensions==4.15.0
      - urllib3==2.5.0
      - visdom==0.2.4
      - wandb==0.16.3
      - wcwidth==0.2.9
      - websocket-client==1.5.1
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.9
      - xxhash==3.2.0
      - yacs==0.1.8
      - yapf==0.33.0
      - yarl==1.9.2
